### ISSUE TITLE
Faulty/buggy client could lock the daemon

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#11]
As described at https://github.com/zero-os/0-db/blob/14df03ca33da20d2fdbe0c6458a334c0177d6ba0/src/socket_epoll.c#L68-L74

and 
https://github.com/zero-os/0-db/blob/14df03ca33da20d2fdbe0c6458a334c0177d6ba0/src/socket_kqueue.c#L61-L67

**Comment by maxux** [comment]
Thanks to have linked this to the issues. This will need some thinking later.

**Comment by iwanbk** [comment]
I saw some fix attempt at 3bae99c80d9712aa8de315e701cfc90d3b124886, what is your plan to fix it @maxux ?

**Comment by maxux** [comment]
The attempt prevent some segmentation fault when a buggy/malformed request was not well checked.

The idea I had is keeping one buffer per client, and keeping each client in non-blocking mode.
The remaining problem with this approche is how to keep the exact status of the client (is it in the middle of a argv parsing, etc.)

**Comment by maxux** [comment]
This need to be tested, but latest commit fix this issue. Will close when tested a little bit more.

**Comment by iwanbk** [comment]
> but latest commit fix this issue.

did a quick check and added few comments to that commit

**Comment by maxux** [comment]
Fixed and closed by #30 and #29
