### ISSUE TITLE
Create an flist for 0-db

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#19]

**Comment by maxux** [comment]
One is available here: https://hub.gig.tech/maxux/zero-db.flist.md

This one will be updated when major changes/fix occures.
The `/zdb` binary is staticly linked.

This binary is get by a simple `make static` version.

**Comment by maxux** [comment]
Gonna do an autobuild script.

**Comment by maxux** [comment]
Autobuild implemented via https://github.com/zero-os/0-db/commit/9a3f363d2f4e57bf3f3c363905d0affbb574153e

Target flist is available here: https://staging.hub.gig.tech/gig-autobuilder/zero-os-0-db-master.flist.md

This flist is updated during any push on master.
