### ISSUE TITLE
need prefab module to build.install.start

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/0-db#2]
- osx & ubuntu

**Comment by zaibon** [comment]
depend on #1

**Comment by maxux** [comment]
Fixed via https://github.com/Jumpscale/prefab9/commit/061b071d71ebd4fcb8c45a2b1ff633b0be615661 and https://github.com/Jumpscale/prefab9/commit/79a5b0ea91bdbcd0c8384cf1691f6c688743c8b3 for OS X
