### ISSUE TITLE
Remove 'busy waiting' when waiting for socket to be available

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#29]
As temporary fix for https://github.com/rivine/0-db/issues/28, we currently do busy waiting below to wait for socket to be available

https://github.com/rivine/0-db/blob/12112f1564906d3cfef3351fdcc0ae36f46cc9e8/src/redis.c#L71-L86

It can give performance penalty for multiple clients

**Comment by maxux** [comment]
@iwanbk can you check the branch `delayed-write` and review the last commit, which should handle this behavior correctly.

If you agree on this way, I'll implement the optimized version to not duplicate non-needed request and adapt the `kqueue` version to this new model.

**Comment by iwanbk** [comment]
looks good.
Some remarks about https://github.com/rivine/0-db/blob/ab23c1dacbaf74f4cd88a659a129838207ee110a/src/commands_get.c#L126-L128

Instead of waiting for `EPOLLOUT` to happens, why not calling `redis_delayed_write` right after `redis_reply`? 

Not sure about this though.

**Comment by maxux** [comment]
Thanks !

Yep, this will be part of the optimization, if this works correctly for all
use cases, need to see with kqueue how to deal with it too.

**Comment by maxux** [comment]
@iwanbk Can you review this commit which implement this: https://github.com/rivine/0-db/pull/30/commits/ab23c1dacbaf74f4cd88a659a129838207ee110a

**Comment by iwanbk** [comment]
LGTM

**Comment by maxux** [comment]
Fixed via #30
