### ISSUE TITLE
AUTH command

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#4]
The `AUTH` command will be used to authenticate a user against the server and allow him to work on a namespace.
So one the client connects to 0-db, it send an `AUTH` command, the password used in the command will map to a namespace, if the command succeed, all the following call to SET/GET/... will work against the mapping namespace.

**Comment by maxux** [comment]
At the end, this will be served by `SELECT` command, which is more accurate for this purpose. We will support an extra optional argument for the password.

We can, in the meantime, use `AUTH` for administrative commands.

**Comment by zaibon** [comment]
Sounds good

**Comment by maxux** [comment]
Authentification implemented in https://github.com/zero-os/0-db/commit/60b2e0f50d818b216e17529d9d15bfe3aac5af1c
Namespace selection implemented in https://github.com/zero-os/0-db/commit/719614577e2868009d51da702d790a39bf20c4d1

**Comment by maxux** [comment]
Closing, since it's seems good. Any bug/crash/improvement should be in dedicated new issues.
