### ISSUE TITLE
Add merge operation

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#42]
There is some use case where we need to upload the object in chunks, because it is too big to be uploaded at once. This use case is described at https://github.com/gigforks/minio/issues/68.

To summarise:
- user upload the object in multiple parts, may not in consecutive order
- in the end, user send command to merge the multiple parts previously uploaded into single object.

I honestly not sure whether this FR is make sense to for 0-db.

**Comment by maxux** [comment]
From the use case described, I see:
- when merging, we do read then write

Actually, doing it in client point of view or internally by sending a `MERGE` command, except the network overhead, it will be the same impact and I don't think it will be really more `efficient` to do it internally.

And in addition, I think you're right, this should not be related/part of 0-db itself:
- Keys are all completely individual and have no links together, in a db point of view
- This would obviously introduce complexity and relation between keys, and I would like to avoid that

**Comment by zaibon** [comment]
> it will be the same impact and I don't think it will be really more efficient to do it internally.

I don't think that is really true. Allowing to avoid to resend all the data over the network would make things much much faster. But still I don't think this is enough to introduce that level of complexity in 0db. The use case can be implemented in many other ways

**Comment by iwanbk** [comment]
> This would obviously introduce complexity and relation between keys, and I would like to avoid that

This was my idea, to create a kind of relation between keys, so we could avoid read-write cycle.
But you're right, it would add complexity.

So, the only way that make sense is to do read-write internally, which i think will not add complexity, no?
While i don't think that it would add complexity, i think it would block the 0-db to serve the other requests for quite a long time, which is not good.

**Comment by iwanbk** [comment]
Closing this issue because it is only needed in edge case and yet not efficient
