### ISSUE TITLE
support hostname for the --listen flag

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#55]
It seems 0-db cannot cope with hostname in the `--listen` flag.
If I start zdb like this `zdb --listen localhost --port 9900 --index /tmp/zdb-index --data /tmp/zdb-data --mode user -v`
Then I cannot connect to it.
While if I use `127.0.0.1` instead of `localhost` things works properly

**Comment by maxux** [comment]
To support hostnames, static binaries will be less portable, but this should not be a big deal.
