### ISSUE TITLE
Command to walk forward and backward

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-db#6]
A user should be able to walk over all the data from a namespace, both forward and backwards.
So from a specific entry, we can or know the next one or the previous one.

for backward walk, implementation wise, this would require to also store the offest of the previous entry, or the size of the previous entry.

API wise, redis protocol already provide SCAN command, maybe we can add a RSCAN for the backward walking

**Comment by iwanbk** [comment]
Do we have ETA for this @maxux ?

**Comment by maxux** [comment]
I hope 2 days max.

**Comment by maxux** [comment]
First complete working `SCAN` and `RSCAN` is implemented at https://github.com/zero-os/0-db/commit/820c937eb1de6832f548ecdf9889721a1b1bd62e

`SCAN` and `RSCAN` needs an argument, which is a key.
- `SCAN` will gives you the key inserted just after the key requested
- `RSCAN` will gives you the key inserted just before the key requested

Note: right now, **deleted keys** are not ignored. Need to improve.

This is the first version which gives correct values from my tests, some tests are welcome. Theses commands are unstable.

Theses two commands act like `SCAN` in original redis protocol. The response is an array of 2 entries:
- First entry is the next key
- Second entry is (again) the next key.
This redundancy is to keep backward compatibility with redis protocol. Like the real `SCAN` command, you just need to redo `SCAN` using the first argument to walk over dataset, except that only one key will be returned at a time.

**Comment by maxux** [comment]
Since b6fceca84d230a9a97326eae04cb694dc76e6473, deleted keys should be handled correctly.

**Comment by maxux** [comment]
Closing, open a new issue if bugs are discovered.
