### ISSUE TITLE
Why not use libev or similar to wrap epoll & kqueue

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/0-db#9]
I see we have `socket_epoll.c` for linux and `socket_kqueue.c` for apple, with some code duplication there.

Why not using `libev` or other similar libs to wrap it?

**Comment by maxux** [comment]
Except if we have any real benefit to use them, for now, there is no real advantage. One advantage to `0-db` is having no-dependencies at all.

**Comment by iwanbk** [comment]
The only benefit i can see so far is to avoid code duplication which currently happens on socket_epoll.c and socket_kqueue.c.

But yeah, those files are relatively small.

**Comment by maxux** [comment]
I flag this issue as `won't fix` and close it, but feel free to reopen it if any benefit comes with time :)
It anyway a good suggestion for later.
